const { Parser } = require('json2csv');

const exportToCSV = (data, fields, filename, user) => {
    try {
        const parser = new Parser({ fields });
        const csv = parser.parse(data);

        const metadata = `# Generated by: ${user}\n# Generated on: ${new Date().toISOString()}\n\n`;
        return metadata + csv;
    } catch (error) {
        throw new Error(`CSV export failed: ${error.message}`);
    }
};

module.exports = exportToCSV;
