const PDFDocument = require('pdfkit');

const exportToPDF = (data, columns, title, user) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            const chunks = [];

            doc.on('data', chunk => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            // Header
            doc.fontSize(18).text(title, { align: 'center' });
            doc.moveDown();
            doc.fontSize(10).text(`Generated by: ${user}`, { align: 'right' });
            doc.text(`Generated on: ${new Date().toLocaleString()}`, { align: 'right' });
            doc.moveDown();

            // Table
            const tableTop = doc.y;
            const colWidth = (doc.page.width - 100) / columns.length;

            // Headers
            doc.fontSize(10).fillColor('black');
            columns.forEach((col, i) => {
                doc.text(col.header, 50 + i * colWidth, tableTop, {
                    width: colWidth,
                    align: 'left'
                });
            });

            doc.moveDown();
            let y = doc.y;

            // Data rows
            doc.fontSize(9);
            data.forEach((row, rowIndex) => {
                if (y > doc.page.height - 100) {
                    doc.addPage();
                    y = 50;
                }

                columns.forEach((col, i) => {
                    const value = col.key.split('.').reduce((obj, key) => obj?.[key], row) || '';
                    doc.text(String(value), 50 + i * colWidth, y, {
                        width: colWidth,
                        align: 'left'
                    });
                });

                y += 20;
                doc.y = y;
            });

            // Footer
            const pages = doc.bufferedPageRange();
            for (let i = 0; i < pages.count; i++) {
                doc.switchToPage(i);
                doc.fontSize(8).text(
                    `Page ${i + 1} of ${pages.count}`,
                    50,
                    doc.page.height - 50,
                    { align: 'center' }
                );
            }

            doc.end();
        } catch (error) {
            reject(new Error(`PDF export failed: ${error.message}`));
        }
    });
};

module.exports = exportToPDF;
